<%@ Page Language="C#" AutoEventWireup="true" CodeFile="05-ControlDetailsView.aspx.cs" Inherits="_05_ControlDetailsView" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Página sin título</title>
    <style type="text/css">


        .style1
        {
            color: #FF0000;
            font-weight: bold;
            text-align: center;
        }
        </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
    <div>
    
    <p class="style1">
        Ejemplo de Uso de DetailsView</p>
            <p>
                <asp:SqlDataSource ID="SdsArticulos" runat="server" 
                    ConnectionString="Data Source=. ;Initial Catalog = Ventas; Integrated Security=true" 
                    DeleteCommand="Delete from Articulos where CodArt=@codigo" 
                    ProviderName="System.Data.SqlClient" SelectCommand="select * from Articulos">
                    <DeleteParameters>
                        <asp:ControlParameter ControlID="DvArticulos" DefaultValue="0" Name="codigo" 
                            PropertyName="SelectedValue" />
                    </DeleteParameters>
                </asp:SqlDataSource>
        </p>
    <asp:Label ID="LblError" runat="server"></asp:Label>
    
        <asp:DetailsView ID="DvArticulos" runat="server" AllowPaging="True" 
            AutoGenerateDeleteButton="True" BackColor="LightGoldenrodYellow" 
            BorderColor="Tan" BorderWidth="1px" Caption="Articulo" CellPadding="2" 
            DataKeyNames="CodArt" DataSourceID="SdsArticulos" ForeColor="Black" 
            GridLines="None" Height="76px" Width="185px">
            <AlternatingRowStyle BackColor="PaleGoldenrod" />
            <EditRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
            <FooterStyle BackColor="Tan" />
            <HeaderStyle BackColor="Tan" Font-Bold="True" />
            <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" 
                HorizontalAlign="Center" />
        </asp:DetailsView>
    
    </div>
        <p>
            <asp:LinkButton ID="LBtnVolver" runat="server" PostBackUrl="~/Default.aspx">Volver</asp:LinkButton>
        </p>
    
    </div>
    </form>
</body>
</html>
