//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.1.
// 
#pragma warning disable 1591

namespace PresentacionWin.ServicioWeb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MiServicioSoap", Namespace="http://tempuri.org/")]
    public partial class MiServicio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ParaPoderSerializarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ParaPoderSerializarCAOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogueoClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarTodosClientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaCuentasDeClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaMovsDeClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarTodasCuentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarCuentaCorrienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarMovimientosDeCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogueoEmpleadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaMovimientoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarTodosMovimientosOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaPrestamoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListoPrestamosClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListoTodosPrestamosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MiServicio() {
            this.Url = global::PresentacionWin.Properties.Settings.Default.PresentacionWin_ServicioWeb_MiServicio;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ParaPoderSerializarCompletedEventHandler ParaPoderSerializarCompleted;
        
        /// <remarks/>
        public event ParaPoderSerializarCACompletedEventHandler ParaPoderSerializarCACompleted;
        
        /// <remarks/>
        public event AltaClienteCompletedEventHandler AltaClienteCompleted;
        
        /// <remarks/>
        public event BajaClienteCompletedEventHandler BajaClienteCompleted;
        
        /// <remarks/>
        public event ModificarClienteCompletedEventHandler ModificarClienteCompleted;
        
        /// <remarks/>
        public event BuscarClienteCompletedEventHandler BuscarClienteCompleted;
        
        /// <remarks/>
        public event LogueoClienteCompletedEventHandler LogueoClienteCompleted;
        
        /// <remarks/>
        public event ListarTodosClientesCompletedEventHandler ListarTodosClientesCompleted;
        
        /// <remarks/>
        public event ListaCuentasDeClienteCompletedEventHandler ListaCuentasDeClienteCompleted;
        
        /// <remarks/>
        public event ListaMovsDeClienteCompletedEventHandler ListaMovsDeClienteCompleted;
        
        /// <remarks/>
        public event AltaCuentaCompletedEventHandler AltaCuentaCompleted;
        
        /// <remarks/>
        public event BajaCuentaCompletedEventHandler BajaCuentaCompleted;
        
        /// <remarks/>
        public event BuscarCuentaCompletedEventHandler BuscarCuentaCompleted;
        
        /// <remarks/>
        public event ListarTodasCuentasCompletedEventHandler ListarTodasCuentasCompleted;
        
        /// <remarks/>
        public event ListarCuentaCorrienteCompletedEventHandler ListarCuentaCorrienteCompleted;
        
        /// <remarks/>
        public event ListarMovimientosDeCuentaCompletedEventHandler ListarMovimientosDeCuentaCompleted;
        
        /// <remarks/>
        public event LogueoEmpleadoCompletedEventHandler LogueoEmpleadoCompleted;
        
        /// <remarks/>
        public event AltaMovimientoCompletedEventHandler AltaMovimientoCompleted;
        
        /// <remarks/>
        public event ListarTodosMovimientosCompletedEventHandler ListarTodosMovimientosCompleted;
        
        /// <remarks/>
        public event AltaPrestamoCompletedEventHandler AltaPrestamoCompleted;
        
        /// <remarks/>
        public event ListoPrestamosClienteCompletedEventHandler ListoPrestamosClienteCompleted;
        
        /// <remarks/>
        public event ListoTodosPrestamosCompletedEventHandler ListoTodosPrestamosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ParaPoderSerializar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ParaPoderSerializar(CuentaCorriente unaCC, CuentaCAhorro unaCA) {
            this.Invoke("ParaPoderSerializar", new object[] {
                        unaCC,
                        unaCA});
        }
        
        /// <remarks/>
        public void ParaPoderSerializarAsync(CuentaCorriente unaCC, CuentaCAhorro unaCA) {
            this.ParaPoderSerializarAsync(unaCC, unaCA, null);
        }
        
        /// <remarks/>
        public void ParaPoderSerializarAsync(CuentaCorriente unaCC, CuentaCAhorro unaCA, object userState) {
            if ((this.ParaPoderSerializarOperationCompleted == null)) {
                this.ParaPoderSerializarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParaPoderSerializarOperationCompleted);
            }
            this.InvokeAsync("ParaPoderSerializar", new object[] {
                        unaCC,
                        unaCA}, this.ParaPoderSerializarOperationCompleted, userState);
        }
        
        private void OnParaPoderSerializarOperationCompleted(object arg) {
            if ((this.ParaPoderSerializarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParaPoderSerializarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ParaPoderSerializarCA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CuentaCAhorro ParaPoderSerializarCA() {
            object[] results = this.Invoke("ParaPoderSerializarCA", new object[0]);
            return ((CuentaCAhorro)(results[0]));
        }
        
        /// <remarks/>
        public void ParaPoderSerializarCAAsync() {
            this.ParaPoderSerializarCAAsync(null);
        }
        
        /// <remarks/>
        public void ParaPoderSerializarCAAsync(object userState) {
            if ((this.ParaPoderSerializarCAOperationCompleted == null)) {
                this.ParaPoderSerializarCAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParaPoderSerializarCAOperationCompleted);
            }
            this.InvokeAsync("ParaPoderSerializarCA", new object[0], this.ParaPoderSerializarCAOperationCompleted, userState);
        }
        
        private void OnParaPoderSerializarCAOperationCompleted(object arg) {
            if ((this.ParaPoderSerializarCACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParaPoderSerializarCACompleted(this, new ParaPoderSerializarCACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaCliente(Cliente unCliente) {
            this.Invoke("AltaCliente", new object[] {
                        unCliente});
        }
        
        /// <remarks/>
        public void AltaClienteAsync(Cliente unCliente) {
            this.AltaClienteAsync(unCliente, null);
        }
        
        /// <remarks/>
        public void AltaClienteAsync(Cliente unCliente, object userState) {
            if ((this.AltaClienteOperationCompleted == null)) {
                this.AltaClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaClienteOperationCompleted);
            }
            this.InvokeAsync("AltaCliente", new object[] {
                        unCliente}, this.AltaClienteOperationCompleted, userState);
        }
        
        private void OnAltaClienteOperationCompleted(object arg) {
            if ((this.AltaClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaCliente(Cliente unCliente) {
            this.Invoke("BajaCliente", new object[] {
                        unCliente});
        }
        
        /// <remarks/>
        public void BajaClienteAsync(Cliente unCliente) {
            this.BajaClienteAsync(unCliente, null);
        }
        
        /// <remarks/>
        public void BajaClienteAsync(Cliente unCliente, object userState) {
            if ((this.BajaClienteOperationCompleted == null)) {
                this.BajaClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaClienteOperationCompleted);
            }
            this.InvokeAsync("BajaCliente", new object[] {
                        unCliente}, this.BajaClienteOperationCompleted, userState);
        }
        
        private void OnBajaClienteOperationCompleted(object arg) {
            if ((this.BajaClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarCliente(Cliente unCliente) {
            this.Invoke("ModificarCliente", new object[] {
                        unCliente});
        }
        
        /// <remarks/>
        public void ModificarClienteAsync(Cliente unCliente) {
            this.ModificarClienteAsync(unCliente, null);
        }
        
        /// <remarks/>
        public void ModificarClienteAsync(Cliente unCliente, object userState) {
            if ((this.ModificarClienteOperationCompleted == null)) {
                this.ModificarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarClienteOperationCompleted);
            }
            this.InvokeAsync("ModificarCliente", new object[] {
                        unCliente}, this.ModificarClienteOperationCompleted, userState);
        }
        
        private void OnModificarClienteOperationCompleted(object arg) {
            if ((this.ModificarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente BuscarCliente(int pNumCli) {
            object[] results = this.Invoke("BuscarCliente", new object[] {
                        pNumCli});
            return ((Cliente)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarClienteAsync(int pNumCli) {
            this.BuscarClienteAsync(pNumCli, null);
        }
        
        /// <remarks/>
        public void BuscarClienteAsync(int pNumCli, object userState) {
            if ((this.BuscarClienteOperationCompleted == null)) {
                this.BuscarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarClienteOperationCompleted);
            }
            this.InvokeAsync("BuscarCliente", new object[] {
                        pNumCli}, this.BuscarClienteOperationCompleted, userState);
        }
        
        private void OnBuscarClienteOperationCompleted(object arg) {
            if ((this.BuscarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarClienteCompleted(this, new BuscarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogueoCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente LogueoCliente(string pUsu, string pPass) {
            object[] results = this.Invoke("LogueoCliente", new object[] {
                        pUsu,
                        pPass});
            return ((Cliente)(results[0]));
        }
        
        /// <remarks/>
        public void LogueoClienteAsync(string pUsu, string pPass) {
            this.LogueoClienteAsync(pUsu, pPass, null);
        }
        
        /// <remarks/>
        public void LogueoClienteAsync(string pUsu, string pPass, object userState) {
            if ((this.LogueoClienteOperationCompleted == null)) {
                this.LogueoClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogueoClienteOperationCompleted);
            }
            this.InvokeAsync("LogueoCliente", new object[] {
                        pUsu,
                        pPass}, this.LogueoClienteOperationCompleted, userState);
        }
        
        private void OnLogueoClienteOperationCompleted(object arg) {
            if ((this.LogueoClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogueoClienteCompleted(this, new LogueoClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarTodosClientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente[] ListarTodosClientes() {
            object[] results = this.Invoke("ListarTodosClientes", new object[0]);
            return ((Cliente[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarTodosClientesAsync() {
            this.ListarTodosClientesAsync(null);
        }
        
        /// <remarks/>
        public void ListarTodosClientesAsync(object userState) {
            if ((this.ListarTodosClientesOperationCompleted == null)) {
                this.ListarTodosClientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarTodosClientesOperationCompleted);
            }
            this.InvokeAsync("ListarTodosClientes", new object[0], this.ListarTodosClientesOperationCompleted, userState);
        }
        
        private void OnListarTodosClientesOperationCompleted(object arg) {
            if ((this.ListarTodosClientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarTodosClientesCompleted(this, new ListarTodosClientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListaCuentasDeCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cuenta[] ListaCuentasDeCliente(Cliente pCliente) {
            object[] results = this.Invoke("ListaCuentasDeCliente", new object[] {
                        pCliente});
            return ((Cuenta[])(results[0]));
        }
        
        /// <remarks/>
        public void ListaCuentasDeClienteAsync(Cliente pCliente) {
            this.ListaCuentasDeClienteAsync(pCliente, null);
        }
        
        /// <remarks/>
        public void ListaCuentasDeClienteAsync(Cliente pCliente, object userState) {
            if ((this.ListaCuentasDeClienteOperationCompleted == null)) {
                this.ListaCuentasDeClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaCuentasDeClienteOperationCompleted);
            }
            this.InvokeAsync("ListaCuentasDeCliente", new object[] {
                        pCliente}, this.ListaCuentasDeClienteOperationCompleted, userState);
        }
        
        private void OnListaCuentasDeClienteOperationCompleted(object arg) {
            if ((this.ListaCuentasDeClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaCuentasDeClienteCompleted(this, new ListaCuentasDeClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListaMovsDeCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ListaMovsDeCliente(Cliente pCliente) {
            object[] results = this.Invoke("ListaMovsDeCliente", new object[] {
                        pCliente});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ListaMovsDeClienteAsync(Cliente pCliente) {
            this.ListaMovsDeClienteAsync(pCliente, null);
        }
        
        /// <remarks/>
        public void ListaMovsDeClienteAsync(Cliente pCliente, object userState) {
            if ((this.ListaMovsDeClienteOperationCompleted == null)) {
                this.ListaMovsDeClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaMovsDeClienteOperationCompleted);
            }
            this.InvokeAsync("ListaMovsDeCliente", new object[] {
                        pCliente}, this.ListaMovsDeClienteOperationCompleted, userState);
        }
        
        private void OnListaMovsDeClienteOperationCompleted(object arg) {
            if ((this.ListaMovsDeClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaMovsDeClienteCompleted(this, new ListaMovsDeClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaCuenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaCuenta(Cuenta unaCuenta) {
            this.Invoke("AltaCuenta", new object[] {
                        unaCuenta});
        }
        
        /// <remarks/>
        public void AltaCuentaAsync(Cuenta unaCuenta) {
            this.AltaCuentaAsync(unaCuenta, null);
        }
        
        /// <remarks/>
        public void AltaCuentaAsync(Cuenta unaCuenta, object userState) {
            if ((this.AltaCuentaOperationCompleted == null)) {
                this.AltaCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaCuentaOperationCompleted);
            }
            this.InvokeAsync("AltaCuenta", new object[] {
                        unaCuenta}, this.AltaCuentaOperationCompleted, userState);
        }
        
        private void OnAltaCuentaOperationCompleted(object arg) {
            if ((this.AltaCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaCuentaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaCuenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaCuenta(Cuenta unaCuenta) {
            this.Invoke("BajaCuenta", new object[] {
                        unaCuenta});
        }
        
        /// <remarks/>
        public void BajaCuentaAsync(Cuenta unaCuenta) {
            this.BajaCuentaAsync(unaCuenta, null);
        }
        
        /// <remarks/>
        public void BajaCuentaAsync(Cuenta unaCuenta, object userState) {
            if ((this.BajaCuentaOperationCompleted == null)) {
                this.BajaCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaCuentaOperationCompleted);
            }
            this.InvokeAsync("BajaCuenta", new object[] {
                        unaCuenta}, this.BajaCuentaOperationCompleted, userState);
        }
        
        private void OnBajaCuentaOperationCompleted(object arg) {
            if ((this.BajaCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaCuentaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarCuenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cuenta BuscarCuenta(int pNumCta) {
            object[] results = this.Invoke("BuscarCuenta", new object[] {
                        pNumCta});
            return ((Cuenta)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarCuentaAsync(int pNumCta) {
            this.BuscarCuentaAsync(pNumCta, null);
        }
        
        /// <remarks/>
        public void BuscarCuentaAsync(int pNumCta, object userState) {
            if ((this.BuscarCuentaOperationCompleted == null)) {
                this.BuscarCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarCuentaOperationCompleted);
            }
            this.InvokeAsync("BuscarCuenta", new object[] {
                        pNumCta}, this.BuscarCuentaOperationCompleted, userState);
        }
        
        private void OnBuscarCuentaOperationCompleted(object arg) {
            if ((this.BuscarCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarCuentaCompleted(this, new BuscarCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarTodasCuentas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cuenta[] ListarTodasCuentas() {
            object[] results = this.Invoke("ListarTodasCuentas", new object[0]);
            return ((Cuenta[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarTodasCuentasAsync() {
            this.ListarTodasCuentasAsync(null);
        }
        
        /// <remarks/>
        public void ListarTodasCuentasAsync(object userState) {
            if ((this.ListarTodasCuentasOperationCompleted == null)) {
                this.ListarTodasCuentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarTodasCuentasOperationCompleted);
            }
            this.InvokeAsync("ListarTodasCuentas", new object[0], this.ListarTodasCuentasOperationCompleted, userState);
        }
        
        private void OnListarTodasCuentasOperationCompleted(object arg) {
            if ((this.ListarTodasCuentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarTodasCuentasCompleted(this, new ListarTodasCuentasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarCuentaCorriente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CuentaCorriente[] ListarCuentaCorriente() {
            object[] results = this.Invoke("ListarCuentaCorriente", new object[0]);
            return ((CuentaCorriente[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarCuentaCorrienteAsync() {
            this.ListarCuentaCorrienteAsync(null);
        }
        
        /// <remarks/>
        public void ListarCuentaCorrienteAsync(object userState) {
            if ((this.ListarCuentaCorrienteOperationCompleted == null)) {
                this.ListarCuentaCorrienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarCuentaCorrienteOperationCompleted);
            }
            this.InvokeAsync("ListarCuentaCorriente", new object[0], this.ListarCuentaCorrienteOperationCompleted, userState);
        }
        
        private void OnListarCuentaCorrienteOperationCompleted(object arg) {
            if ((this.ListarCuentaCorrienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCuentaCorrienteCompleted(this, new ListarCuentaCorrienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarMovimientosDeCuenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Movimiento[] ListarMovimientosDeCuenta(Cuenta unaCuenta) {
            object[] results = this.Invoke("ListarMovimientosDeCuenta", new object[] {
                        unaCuenta});
            return ((Movimiento[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarMovimientosDeCuentaAsync(Cuenta unaCuenta) {
            this.ListarMovimientosDeCuentaAsync(unaCuenta, null);
        }
        
        /// <remarks/>
        public void ListarMovimientosDeCuentaAsync(Cuenta unaCuenta, object userState) {
            if ((this.ListarMovimientosDeCuentaOperationCompleted == null)) {
                this.ListarMovimientosDeCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarMovimientosDeCuentaOperationCompleted);
            }
            this.InvokeAsync("ListarMovimientosDeCuenta", new object[] {
                        unaCuenta}, this.ListarMovimientosDeCuentaOperationCompleted, userState);
        }
        
        private void OnListarMovimientosDeCuentaOperationCompleted(object arg) {
            if ((this.ListarMovimientosDeCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarMovimientosDeCuentaCompleted(this, new ListarMovimientosDeCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogueoEmpleado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Empleado LogueoEmpleado(int pCI, string pPass) {
            object[] results = this.Invoke("LogueoEmpleado", new object[] {
                        pCI,
                        pPass});
            return ((Empleado)(results[0]));
        }
        
        /// <remarks/>
        public void LogueoEmpleadoAsync(int pCI, string pPass) {
            this.LogueoEmpleadoAsync(pCI, pPass, null);
        }
        
        /// <remarks/>
        public void LogueoEmpleadoAsync(int pCI, string pPass, object userState) {
            if ((this.LogueoEmpleadoOperationCompleted == null)) {
                this.LogueoEmpleadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogueoEmpleadoOperationCompleted);
            }
            this.InvokeAsync("LogueoEmpleado", new object[] {
                        pCI,
                        pPass}, this.LogueoEmpleadoOperationCompleted, userState);
        }
        
        private void OnLogueoEmpleadoOperationCompleted(object arg) {
            if ((this.LogueoEmpleadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogueoEmpleadoCompleted(this, new LogueoEmpleadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaMovimiento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaMovimiento(Movimiento pMovimiento) {
            this.Invoke("AltaMovimiento", new object[] {
                        pMovimiento});
        }
        
        /// <remarks/>
        public void AltaMovimientoAsync(Movimiento pMovimiento) {
            this.AltaMovimientoAsync(pMovimiento, null);
        }
        
        /// <remarks/>
        public void AltaMovimientoAsync(Movimiento pMovimiento, object userState) {
            if ((this.AltaMovimientoOperationCompleted == null)) {
                this.AltaMovimientoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaMovimientoOperationCompleted);
            }
            this.InvokeAsync("AltaMovimiento", new object[] {
                        pMovimiento}, this.AltaMovimientoOperationCompleted, userState);
        }
        
        private void OnAltaMovimientoOperationCompleted(object arg) {
            if ((this.AltaMovimientoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaMovimientoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarTodosMovimientos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Movimiento[] ListarTodosMovimientos() {
            object[] results = this.Invoke("ListarTodosMovimientos", new object[0]);
            return ((Movimiento[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarTodosMovimientosAsync() {
            this.ListarTodosMovimientosAsync(null);
        }
        
        /// <remarks/>
        public void ListarTodosMovimientosAsync(object userState) {
            if ((this.ListarTodosMovimientosOperationCompleted == null)) {
                this.ListarTodosMovimientosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarTodosMovimientosOperationCompleted);
            }
            this.InvokeAsync("ListarTodosMovimientos", new object[0], this.ListarTodosMovimientosOperationCompleted, userState);
        }
        
        private void OnListarTodosMovimientosOperationCompleted(object arg) {
            if ((this.ListarTodosMovimientosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarTodosMovimientosCompleted(this, new ListarTodosMovimientosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaPrestamo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaPrestamo(Prestamo pPrestamo) {
            this.Invoke("AltaPrestamo", new object[] {
                        pPrestamo});
        }
        
        /// <remarks/>
        public void AltaPrestamoAsync(Prestamo pPrestamo) {
            this.AltaPrestamoAsync(pPrestamo, null);
        }
        
        /// <remarks/>
        public void AltaPrestamoAsync(Prestamo pPrestamo, object userState) {
            if ((this.AltaPrestamoOperationCompleted == null)) {
                this.AltaPrestamoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaPrestamoOperationCompleted);
            }
            this.InvokeAsync("AltaPrestamo", new object[] {
                        pPrestamo}, this.AltaPrestamoOperationCompleted, userState);
        }
        
        private void OnAltaPrestamoOperationCompleted(object arg) {
            if ((this.AltaPrestamoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaPrestamoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListoPrestamosCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Prestamo[] ListoPrestamosCliente(Cliente unCliente) {
            object[] results = this.Invoke("ListoPrestamosCliente", new object[] {
                        unCliente});
            return ((Prestamo[])(results[0]));
        }
        
        /// <remarks/>
        public void ListoPrestamosClienteAsync(Cliente unCliente) {
            this.ListoPrestamosClienteAsync(unCliente, null);
        }
        
        /// <remarks/>
        public void ListoPrestamosClienteAsync(Cliente unCliente, object userState) {
            if ((this.ListoPrestamosClienteOperationCompleted == null)) {
                this.ListoPrestamosClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListoPrestamosClienteOperationCompleted);
            }
            this.InvokeAsync("ListoPrestamosCliente", new object[] {
                        unCliente}, this.ListoPrestamosClienteOperationCompleted, userState);
        }
        
        private void OnListoPrestamosClienteOperationCompleted(object arg) {
            if ((this.ListoPrestamosClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListoPrestamosClienteCompleted(this, new ListoPrestamosClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListoTodosPrestamos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Prestamo[] ListoTodosPrestamos() {
            object[] results = this.Invoke("ListoTodosPrestamos", new object[0]);
            return ((Prestamo[])(results[0]));
        }
        
        /// <remarks/>
        public void ListoTodosPrestamosAsync() {
            this.ListoTodosPrestamosAsync(null);
        }
        
        /// <remarks/>
        public void ListoTodosPrestamosAsync(object userState) {
            if ((this.ListoTodosPrestamosOperationCompleted == null)) {
                this.ListoTodosPrestamosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListoTodosPrestamosOperationCompleted);
            }
            this.InvokeAsync("ListoTodosPrestamos", new object[0], this.ListoTodosPrestamosOperationCompleted, userState);
        }
        
        private void OnListoTodosPrestamosOperationCompleted(object arg) {
            if ((this.ListoTodosPrestamosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListoTodosPrestamosCompleted(this, new ListoTodosPrestamosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CuentaCorriente : Cuenta {
        
        private double minimoCtaField;
        
        /// <comentarios/>
        public double MinimoCta {
            get {
                return this.minimoCtaField;
            }
            set {
                this.minimoCtaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CuentaCAhorro))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CuentaCorriente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cuenta {
        
        private int numCtaField;
        
        private Cliente unClienteField;
        
        private double saldoCuentaField;
        
        private string miClienteField;
        
        /// <comentarios/>
        public int NumCta {
            get {
                return this.numCtaField;
            }
            set {
                this.numCtaField = value;
            }
        }
        
        /// <comentarios/>
        public Cliente UnCliente {
            get {
                return this.unClienteField;
            }
            set {
                this.unClienteField = value;
            }
        }
        
        /// <comentarios/>
        public double SaldoCuenta {
            get {
                return this.saldoCuentaField;
            }
            set {
                this.saldoCuentaField = value;
            }
        }
        
        /// <comentarios/>
        public string MiCliente {
            get {
                return this.miClienteField;
            }
            set {
                this.miClienteField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente {
        
        private int numCliField;
        
        private string nomCliField;
        
        private string dirCliField;
        
        private string passCliField;
        
        private string usuCliField;
        
        private string[] listaTelefonosField;
        
        /// <comentarios/>
        public int NumCli {
            get {
                return this.numCliField;
            }
            set {
                this.numCliField = value;
            }
        }
        
        /// <comentarios/>
        public string NomCli {
            get {
                return this.nomCliField;
            }
            set {
                this.nomCliField = value;
            }
        }
        
        /// <comentarios/>
        public string DirCli {
            get {
                return this.dirCliField;
            }
            set {
                this.dirCliField = value;
            }
        }
        
        /// <comentarios/>
        public string PassCli {
            get {
                return this.passCliField;
            }
            set {
                this.passCliField = value;
            }
        }
        
        /// <comentarios/>
        public string UsuCli {
            get {
                return this.usuCliField;
            }
            set {
                this.usuCliField = value;
            }
        }
        
        /// <comentarios/>
        public string[] ListaTelefonos {
            get {
                return this.listaTelefonosField;
            }
            set {
                this.listaTelefonosField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Prestamo {
        
        private int idField;
        
        private Cliente unClienteField;
        
        private System.DateTime fechaField;
        
        private double montoField;
        
        private bool aprobadoField;
        
        private string clienteField;
        
        /// <comentarios/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        public Cliente UnCliente {
            get {
                return this.unClienteField;
            }
            set {
                this.unClienteField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <comentarios/>
        public double Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <comentarios/>
        public bool Aprobado {
            get {
                return this.aprobadoField;
            }
            set {
                this.aprobadoField = value;
            }
        }
        
        /// <comentarios/>
        public string Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Empleado {
        
        private int ciEmpField;
        
        private string nomEmpField;
        
        private string passEmpField;
        
        /// <comentarios/>
        public int CiEmp {
            get {
                return this.ciEmpField;
            }
            set {
                this.ciEmpField = value;
            }
        }
        
        /// <comentarios/>
        public string NomEmp {
            get {
                return this.nomEmpField;
            }
            set {
                this.nomEmpField = value;
            }
        }
        
        /// <comentarios/>
        public string PassEmp {
            get {
                return this.passEmpField;
            }
            set {
                this.passEmpField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Movimiento {
        
        private int idMovField;
        
        private System.DateTime fechaMovField;
        
        private double montoMovField;
        
        private string tipoMovField;
        
        private Cuenta unaCuentaField;
        
        /// <comentarios/>
        public int IdMov {
            get {
                return this.idMovField;
            }
            set {
                this.idMovField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaMov {
            get {
                return this.fechaMovField;
            }
            set {
                this.fechaMovField = value;
            }
        }
        
        /// <comentarios/>
        public double MontoMov {
            get {
                return this.montoMovField;
            }
            set {
                this.montoMovField = value;
            }
        }
        
        /// <comentarios/>
        public string TipoMov {
            get {
                return this.tipoMovField;
            }
            set {
                this.tipoMovField = value;
            }
        }
        
        /// <comentarios/>
        public Cuenta UnaCuenta {
            get {
                return this.unaCuentaField;
            }
            set {
                this.unaCuentaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CuentaCAhorro : Cuenta {
        
        private int movsCtaField;
        
        private double costoMovsCtaField;
        
        /// <comentarios/>
        public int MovsCta {
            get {
                return this.movsCtaField;
            }
            set {
                this.movsCtaField = value;
            }
        }
        
        /// <comentarios/>
        public double CostoMovsCta {
            get {
                return this.costoMovsCtaField;
            }
            set {
                this.costoMovsCtaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ParaPoderSerializarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ParaPoderSerializarCACompletedEventHandler(object sender, ParaPoderSerializarCACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ParaPoderSerializarCACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ParaPoderSerializarCACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CuentaCAhorro Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CuentaCAhorro)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AltaClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BajaClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ModificarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BuscarClienteCompletedEventHandler(object sender, BuscarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LogueoClienteCompletedEventHandler(object sender, LogueoClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogueoClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogueoClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListarTodosClientesCompletedEventHandler(object sender, ListarTodosClientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarTodosClientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarTodosClientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListaCuentasDeClienteCompletedEventHandler(object sender, ListaCuentasDeClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaCuentasDeClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaCuentasDeClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cuenta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cuenta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListaMovsDeClienteCompletedEventHandler(object sender, ListaMovsDeClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaMovsDeClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaMovsDeClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AltaCuentaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BajaCuentaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BuscarCuentaCompletedEventHandler(object sender, BuscarCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cuenta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cuenta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListarTodasCuentasCompletedEventHandler(object sender, ListarTodasCuentasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarTodasCuentasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarTodasCuentasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cuenta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cuenta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListarCuentaCorrienteCompletedEventHandler(object sender, ListarCuentaCorrienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCuentaCorrienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCuentaCorrienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CuentaCorriente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CuentaCorriente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListarMovimientosDeCuentaCompletedEventHandler(object sender, ListarMovimientosDeCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarMovimientosDeCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarMovimientosDeCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Movimiento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Movimiento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LogueoEmpleadoCompletedEventHandler(object sender, LogueoEmpleadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogueoEmpleadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogueoEmpleadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empleado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empleado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AltaMovimientoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListarTodosMovimientosCompletedEventHandler(object sender, ListarTodosMovimientosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarTodosMovimientosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarTodosMovimientosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Movimiento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Movimiento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AltaPrestamoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListoPrestamosClienteCompletedEventHandler(object sender, ListoPrestamosClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListoPrestamosClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListoPrestamosClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Prestamo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Prestamo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListoTodosPrestamosCompletedEventHandler(object sender, ListoTodosPrestamosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListoTodosPrestamosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListoTodosPrestamosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Prestamo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Prestamo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591